### ISSUE TITLE
Auto page build is failing

### ISSUE THREAD

**Issue by mondus** [FLAME-HPC/FLAME-HPC.github.io#3]
Not sure why as it builds locally.

**Comment by glpoulter** [comment]
I'm finding this as well, will test locally with as close to a github pages setup as possible.

**Comment by glpoulter** [comment]
I installed locally using the same Gemfile as GitHub Pages gem. The build then failed with an error regarding the plugins line on the the config file. As the entry here was actually just the default for plugins I removed it and builds are now fine. https://github.com/FLAME-HPC/FLAME-HPC.github.io/commit/f5e89bf9c0133f3f989cb67c739f3665186f9e2b
